"""empty message

Revision ID: 3e0b1d29e228
Revises: 71f6e1fa1dae
Create Date: 2020-12-23 11:25:06.382661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e0b1d29e228'
down_revision = '71f6e1fa1dae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.String(), nullable=True))
    op.drop_column('venue', 'geners')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('geners', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###
